# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhoWants' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'lottie-ios'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  # Pods for WhoWants


  target 'WhoWantsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WhoWantsUITests' do
    # Pods for testing
  end

end
